services:
  api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./server:/usr/src/app/server
    depends_on:
      - db
      - redis
    environment:
      # Read the variables from the .env file
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}

  db:
    image: postgres:16-alpine
    environment:
      # Read the variables from the .env file
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
